### PR TITLE
Revert "build: install wheel from Cockpit git main"

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This reverts commit 60d5f71c083be74659c9273aac97e00da2881fa3.

fsinfo is now available in all of our testing images.

### CODE REVIEW

**Comment by martinpitt** [comment]
:tada progress!

To make this complete, please bump the bridge dependency both in the manifest and also in debian/control and spec.

**Comment by allisonkarlitskaya** [comment]
> 🎉 progress!
> 
> To make this complete, please bump the bridge dependency both in the manifest and also in debian/control and spec.

Right!  Thanks for the reminder.

**Review by martinpitt — APPROVED** [review]
Thanks! WFM once rawhide goes green, or alternatively you lower to `>= 310` (which is technically correct)

**Comment by allisonkarlitskaya** [comment]
[That didn't go as well as expected](https://github.com/cockpit-project/bots/issues/5886), so 310, I guess.

**Comment by martinpitt** [comment]
[This disaster](https://cockpit-logs.us-east-1.linodeobjects.com/pull-260-20240208-084157-c9ebb6df-fedora-rawhide/log.html) is almost surely because the run saw the broken selinux, but not the [fixed cockpit 300.2](https://bodhi.fedoraproject.org/updates/FEDORA-2024-a750c178ad) yet. Unfortunately the log doesn't give the bridge version

**Comment by allisonkarlitskaya** [comment]
> [This disaster](https://cockpit-logs.us-east-1.linodeobjects.com/pull-260-20240208-084157-c9ebb6df-fedora-rawhide/log.html) is almost surely because the run saw the broken selinux, but not the [fixed cockpit 300.2](https://bodhi.fedoraproject.org/updates/FEDORA-2024-a750c178ad) yet. Unfortunately the log doesn't give the bridge version

It was this:

```
cockpit.packages-DEBUG: Considering file /usr/share/cockpit/navigator/manifest.json
cockpit.config-DEBUG: lookup_config(navigator.override.json): defaulting to /etc/cockpit/navigator.override.json
cockpit.packages-WARNING: /usr/share/cockpit/navigator/manifest.json required cockpit version (310.1) not met
```

...of course.  :facepalm:

**Review by jelly — APPROVED** [review]

**Pull request merged**
