### PR TITLE
Make symlinks to directories icon blue

### PR DESCRIPTION
**Pull request by tomasmatus**
fixes: #147
Treat symbolic links to directories like a normal directory and make the folder icon blue.

### CODE REVIEW

**Review by subhoghoshX — COMMENTED** [review]
Thanks :) Fixing the sorting would be great as well. Like in the below image /bin should be placed first in a-z order.

image

**Review by KKoukiou — APPROVED** [review]

**Comment by jelly** [comment]
Interesting, I think most file managers show at least an icon that it's a symlink. So I think we should do something similar here. Note that it's unrelated to folder color.

image

**Comment by KKoukiou** [comment]
> Interesting, I think most file managers show at least an icon that it's a symlink. So I think we should do something similar here. Note that it's unrelated to folder color.
> 
> image

There is another issue about that https://github.com/cockpit-project/cockpit-navigator/issues/67

**Comment by tomasmatus** [comment]
@subhoghoshX yeah, right. I didn't realize the ordering is also wrong :) should be fixed now!

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
